### ISSUE TITLE
Push the new git tag

### ISSUE THREAD

**Issue by dmitrykiselyov** [hashobject/lt-stylus#3]
Push the new git tag 0.0.3 http://docs.lighttable.com/#submit-a-plugin. Сurrent tag is 0.0.2
https://github.com/LightTable/plugin-metadata/issues/27#issuecomment-83536349

**Comment by podviaznikov** [comment]
Done. Thanks for updating plugin repository: https://github.com/LightTable/plugin-metadata/issues/27!
